apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
        - name: gitops-app
          image: 952365419830.dkr.ecr.ap-south-1.amazonaws.com/gitops-demo:5ae5ca067b3d1494855eb6a42c79c0f2eeaae544
          ports:
            - containerPort: 8080
