apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
        - name: gitops-app
          image: 952365419830.dkr.ecr.ap-south-1.amazonaws.com/gitops-demo:bef90217c0d80034f2858e804e69a79cd4257dde
          ports:
            - containerPort: 8080
